### ISSUE TITLE
Umbrella Ticket: API access, interpretation, and display

### ISSUE THREAD

**Issue by davidk-im** [0404btruong/p2-hardstuck#8]
David
- [x] access pure data from api, pull data from json
- [x] put some areas in api display that accesses api without intepretation
- [x] use methods from classes to calculate basic data from pure data from api
- [ ] format everything on html
- [ ] use css to make it look nice

Links to code: (still in progress, as python does not fully integrate with html at the moment)
